import type { NextPage } from 'next'
import Head from 'next/head'

const Register: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Register />
      </main>

      <footer>
        This is a footer
      </footer>
    </div>
  )
}

export default Register
