import type { NextPage } from "next";
import Head from "next/head";
import { RegisterFlow } from "../components/register/RegisterFlow";
import { Layout } from "../components/shared/Layout";

const Register: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <RegisterFlow />
      </main>

      <footer>This is a footer</footer>
    </Layout>
  );
};

export default Register;
